// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function Game(props) {
  var difficulty = props.difficulty;
  console.log("This will be a " + difficulty + " game");
  var match = React.useState(function () {
        return false;
      });
  var setShowQuitForm = match[1];
  var backgroundStyle = {
    backgroundImage: "url('/gamecolor.jpg')",
    backgroundPosition: "center",
    height: "100vh",
    position: "relative",
    width: "100vw",
    backgroundSize: "cover"
  };
  return JsxRuntime.jsx("div", {
              children: match[0] ? JsxRuntime.jsxs("div", {
                      children: [
                        JsxRuntime.jsx("h2", {
                              children: "Are you sure you want to quit?",
                              className: "text-2xl font-semibold mb-4"
                            }),
                        JsxRuntime.jsxs("div", {
                              children: [
                                JsxRuntime.jsx(Button.make, {
                                      className: "px-10 py-2 bg-red-500 text-white font-bold rounded",
                                      onClick: (function (param) {
                                          RescriptReactRouter.push("/");
                                        }),
                                      children: "Yes"
                                    }),
                                JsxRuntime.jsx(Button.make, {
                                      className: "px-10 py-2 bg-green-500 text-white font-bold rounded",
                                      onClick: (function (param) {
                                          setShowQuitForm(function (param) {
                                                return false;
                                              });
                                        }),
                                      children: "No"
                                    })
                              ],
                              className: "flex justify-between mt-6"
                            })
                      ],
                      style: {
                        backgroundColor: "white",
                        left: "50%",
                        padding: "20px",
                        position: "absolute",
                        textAlign: "center",
                        top: "50%",
                        borderRadius: "8px",
                        boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
                        transform: "translate(-50%, -50%)"
                      }
                    }) : JsxRuntime.jsxs(JsxRuntime.Fragment, {
                      children: [
                        JsxRuntime.jsx(Button.make, {
                              className: "absolute bottom-4 left-4 px-4 py-2 bg-yellow-400 text-black font-bold rounded",
                              onClick: (function (param) {
                                  setShowQuitForm(function (param) {
                                        return true;
                                      });
                                }),
                              children: "Quit"
                            }),
                        JsxRuntime.jsx("h1", {
                              children: "Game Page for " + difficulty + " Difficulty",
                              style: {
                                color: "white",
                                textAlign: "center"
                              }
                            })
                      ]
                    }),
              style: backgroundStyle
            });
}

var make = Game;

export {
  make ,
}
/* react Not a pure module */
