// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function StartBackground(props) {
  var backgroundStyle = {
    backgroundImage: "url('/background.jpg')",
    backgroundPosition: "center",
    height: "100vh",
    width: "100vw",
    backgroundSize: "cover"
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx("h1", {
                    children: "Welcome to UNO!"
                  }),
              style: backgroundStyle
            });
}

var make = StartBackground;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
