// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Button from "../Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function StartBackground(props) {
  var backgroundStyle = {
    backgroundImage: "url('/background.jpg')",
    backgroundPosition: "center",
    display: "flex",
    height: "100vh",
    width: "100vw",
    backgroundSize: "cover",
    alignItems: "center",
    justifyContent: "center"
  };
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsxs("div", {
                    children: [
                      JsxRuntime.jsx("h1", {
                            className: "text-4xl font-bold text-white mb-6"
                          }),
                      JsxRuntime.jsx(Button.make, {
                            children: "Start Game",
                            onClick: (function (param) {
                                console.log("Button Clicked!");
                              })
                          })
                    ]
                  }),
              style: backgroundStyle
            });
}

var make = StartBackground;

export {
  make ,
}
/* Button Not a pure module */
