// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as Button from "../Button.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";
import * as RescriptReactRouter from "@rescript/react/src/RescriptReactRouter.res.mjs";

function StartBackground(props) {
  var match = React.useState(function () {
        return false;
      });
  var setShowForm = match[1];
  var showForm = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setSelectedDifficulty = match$1[1];
  var selectedDifficulty = match$1[0];
  var backgroundStyle = {
    backgroundImage: "url('/background.jpg')",
    backgroundPosition: "center",
    display: "flex",
    height: "100vh",
    paddingBottom: "16vh",
    width: "100vw",
    backgroundSize: "cover",
    alignItems: "flex-end",
    justifyContent: "center"
  };
  var handleFormStartClick = function () {
    if (selectedDifficulty !== undefined) {
      return RescriptReactRouter.push("/game/" + selectedDifficulty);
    } else {
      console.log("Please select a difficulty level");
      return ;
    }
  };
  var isSelected = function (difficulty) {
    if (selectedDifficulty !== undefined) {
      return selectedDifficulty === difficulty;
    } else {
      return false;
    }
  };
  return JsxRuntime.jsxs("div", {
              children: [
                JsxRuntime.jsx("div", {
                      children: showForm ? null : JsxRuntime.jsx(Button.make, {
                              onClick: (function (param) {
                                  setShowForm(function (param) {
                                        return true;
                                      });
                                }),
                              children: "Start Game"
                            }),
                      style: {
                        textAlign: "center"
                      }
                    }),
                showForm ? JsxRuntime.jsxs("div", {
                        children: [
                          JsxRuntime.jsx("h2", {
                                children: "Select Your Difficulty Level",
                                className: "text-2xl font-semibold mb-4"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx(Button.make, {
                                        className: isSelected("Easy") ? "px-4 py-2 bg-blue-500 text-white font-bold rounded" : "px-4 py-2 bg-yellow-400 text-black rounded",
                                        onClick: (function (param) {
                                            setSelectedDifficulty(function (param) {
                                                  return "Easy";
                                                });
                                          }),
                                        children: "Easy"
                                      }),
                                  JsxRuntime.jsx(Button.make, {
                                        className: isSelected("Medium") ? "px-4 py-2 bg-blue-500 text-white font-bold rounded" : "px-4 py-2 bg-yellow-400 text-black rounded",
                                        onClick: (function (param) {
                                            setSelectedDifficulty(function (param) {
                                                  return "Medium";
                                                });
                                          }),
                                        children: "Medium"
                                      }),
                                  JsxRuntime.jsx(Button.make, {
                                        className: isSelected("Hard") ? "px-4 py-2 bg-blue-500 text-white font-bold rounded" : "px-4 py-2 bg-yellow-400 text-black rounded",
                                        onClick: (function (param) {
                                            setSelectedDifficulty(function (param) {
                                                  return "Hard";
                                                });
                                          }),
                                        children: "Hard"
                                      })
                                ],
                                className: "flex flex-col gap-4"
                              }),
                          JsxRuntime.jsxs("div", {
                                children: [
                                  JsxRuntime.jsx(Button.make, {
                                        className: "px-4 py-2 bg-red-500 text-white font-bold rounded",
                                        onClick: (function (param) {
                                            setShowForm(function (param) {
                                                  return false;
                                                });
                                          }),
                                        children: "Cancel"
                                      }),
                                  JsxRuntime.jsx(Button.make, {
                                        className: "px-4 py-2 bg-green-500 text-white font-bold rounded",
                                        onClick: (function (param) {
                                            handleFormStartClick();
                                          }),
                                        children: "Start"
                                      })
                                ],
                                className: "flex justify-between mt-6"
                              })
                        ],
                        style: {
                          backgroundColor: "white",
                          left: "50%",
                          padding: "20px",
                          position: "absolute",
                          textAlign: "center",
                          top: "50%",
                          borderRadius: "8px",
                          boxShadow: "0 4px 6px rgba(0, 0, 0, 0.1)",
                          transform: "translate(-50%, -50%)"
                        }
                      }) : null
              ],
              style: backgroundStyle
            });
}

var make = StartBackground;

export {
  make ,
}
/* react Not a pure module */
