// Generated by ReScript, PLEASE EDIT WITH CARE

import * as StartBackground from "./components/StartBackground.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(StartBackground.make, {})
            });
}

var make = App;

export {
  make ,
}
/* StartBackground Not a pure module */
