// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  var className = props.className;
  var finalClassName = className !== undefined ? className : "inline-block px-6 py-2.5 bg-yellow-400 text-black font-medium text-xs leading-tight uppercase rounded shadow-md hover:bg-yellow-600 hover:shadow-lg focus:bg-yellow-600 focus:shadow-lg focus:outline-none focus:ring-0 active:bg-yellow-700 active:shadow-lg transition duration-150 ease-in-out";
  return JsxRuntime.jsx("button", {
              children: props.children,
              className: finalClassName,
              onClick: props.onClick
            });
}

var make = Button;

export {
  make ,
}
/* react/jsx-runtime Not a pure module */
